version: '3.8'

services:
  app:
    build:
      context: .
      args:
        GIT_USERNAME: your_username
        GIT_PASSWORD: your_password
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb://mongo:27017/mydatabase
    networks:
      - go-mongo-network

  mongo:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - go-mongo-network

volumes:
  mongo-data:

networks:
  go-mongo-network:
